sigir-ecom/sigir-ecom.github.io

data-task.html
I added the data challenge description, evaluation, time line, etc. Please merge the change, thanks!
=> Adding data challenge detail Version 1.

data-task.html
I updated the data challenge description and added the submission part. Please merge the change, thanks!
=> Updating data challenge Version 2.

data-task.html
Updating evaluation description in data-task.html, please merge the changes. Thank you!
=> Updating evaluation description.

data-task.html
Submission rules have been added, please merge the changes.
=> Adding submission rules.

data-task.html
I added the details about system description paper, please merge the change.
=> Adding system description paper section

data-task.html
I added the paper submission link, please merge the change.
=> Adding paper submission link.

data-task.html
Please merge the change, thank you!
=> Updating paper submission deadline.

accepted-papers.html, cfp.html, data-task.html, index.html, organizers.html, program.html
I removed the "dates" and "topics" tabs from the header and added "accepted papers" so that the line does not break. The "accepted papers" page was added, too. Please check it and merge the change.
=> Adding accepted papers page.

data-task.html
I changed the width and height to fit the new leaderboard size. Please merge the change.
=> Changing leaderboard frame width and height

data-task.html
Moved leaderboard to the top. Please merge the change.
=> Moving leaderboard above the about section.

data-task.html
I increased the frame height. Please merge the change.
=> Increasing frame height.

data-task.html
Extending camera ready deadline to July 6. Please merge the change.
=> Extending camera ready deadline to July 6.

data-task.html
The file `data_challenge.html` is edited to include the description and participation instructions for the challenge.
=> Rakuten data challenge

data-task.html
Hello,
Please accept this version with a small text modification.
Thanks.
=> minor text modifications

data-task.html
=> Coveo data challenge

data-task.html
@skallumadi, could you please replace "All submissions should be made at XXXX " with the appropriate submission URL, and also verify/update the required submission format as required. Thanks!
=> update details for paper submission

data-task.html
Update stage 1 & 2 closing dates
Remove Sign-up
Update info on submission link
=> closing date updates and remove sign up

data-task.html
Add paper submission link
Enable Stage 2 Leaderboard
Update timeline progress
=> Stage 2 Updates

data-task.html
=> Update paper submission deadline

data-task.html
This PR adds a section with instructions for Paper Submission and an alert for that in the beginning of the page as well.
It looks like this:
=> feat: add paper submissions

data-task.html
This PR includes the Final Standings for the Outfits challenge.
The table will look like the following:
=> feat: add final standings

index.html
You can preview the changes at [https://aditya-chichani.github.io/](https://aditya-chichani.github.io/)
=> Added schedule
